import path from 'node:path'

export default {
  unstyled: true,
  // import and apply presets globally
  importPT: { from: path.resolve(__dirname, './presets/') },
  components: {
    include: [
      'Autocomplete',
      'Accordion',
      'AccordionTab',
      'Checkbox',
      'Dropdown',
      'InputGroup',
      'InputGroupAddon',
      'InputText',
      'InputNumber',
      'InputMask',
      'InputSwitch',
      'MultiSelect',
      'Password',
      'RadioButton',
      'SelectButton',
      'Textarea',
      'Button',
      'SplitButton',
      'Card',
      'Divider',
      'TabView',
      'Panel',
      'ConfirmPopup',
      'Dialog',
      'Tooltip',
      'Paginator',
      'Breadcrumb',
      'Menu',
      'Menubar',
      'Steps',
      'TabMenu',
      'Message',
      'InlineMessage',
      'Toast',
      'Skeleton',
      'Avatar',
      'Badge',
      'Tag',
      'DataTable',
      'Column',
    ],
  },
}
